MVCDemo/Models/ErrorViewModel.cs
namespace MVCDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCDemo/Models/Fever.cs
using System.ComponentModel.DataAnnotations;

namespace MVCDemo.Models
{
    public class Fever
    {
        //data annotation

        [Display(Name = "Body Temperatuer")]
        public double BTemp { get; set; }
        public string TestResult { get; set; }
    }
}

MVCDemo/Models/GuessNumber.cs
using System.ComponentModel.DataAnnotations;

namespace MVCDemo.Models
{
    public class GuessNumber
    {
        public int SecretNum { get; set; }

        [Display(Name = "Your guess")]
        public int GuessNum { get; set; }
        public string Msg { get; set; }

       
    }
}

MVCDemo/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace MVCDemo.Models
{
    public class Student
    {
        [Required]
        public int SId { get; set; }
       
        [Required]
        public string Name { get; set;}
        
        [Required]
        public string Gender { get; set; }
        
        [Required]
        public int Age { get; set;}

        //[Required]
        //[DataType(DataType.PhoneNumber)]
        //[StringLength(25)]
        //public string Phone { get; set;}

        public Student()
        {
            
        }
        public Student(int Id, string name, string gender, int age)
        {
            SId = Id;
            Name = name;
            Gender = gender;
            Age = age;
        }
    }
}

MVCDemo/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Models;
using Newtonsoft.Json;
using System;

namespace MVCDemo.Controllers
{
    public class AssignmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult FeverCheck()
        {
            Fever obj = new Fever(); 
            return View(obj);
        }

        [HttpPost]
        public IActionResult FeverCheck(Fever obj)
        {
            if (obj.BTemp > 37.2)
            {
                obj.TestResult = "You have fever.";
            }
            else
            {
                obj.TestResult = "All right! no fever.";
            }
            return View(obj);
        }

        public IActionResult GuessGame()
        {
            GuessNumber obj = new GuessNumber();
            Random rnd = new Random();

            int sNum = rnd.Next(1,501);
            obj.SecretNum = sNum;
            HttpContext.Session.SetInt32("sNumber", sNum);
            return View(obj);
        }

        [HttpPost]
        public IActionResult GuessGame(GuessNumber obj)
        {
            obj.SecretNum = (int)HttpContext.Session.GetInt32("sNumber");

            if (obj.GuessNum > obj.SecretNum)
            {
                obj.Msg = "Your guess is high!";
            }
            else if (obj.GuessNum < obj.SecretNum)
            {
                obj.Msg = "Your guess is low!";
            }
            else 
            {
                obj.Msg = "You guessed it correct!!";
                HttpContext.Session.Clear();
            }
            return View(obj);
        }
    }
}

MVCDemo/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCDemo.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Models;
using System.Diagnostics;

namespace MVCDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["greet"] = "Hello MVC Application";
            ViewBag.vbMSG = "Passing Message through the ViewBag";
            ViewData["vdMSG"] = "Passing Message through the ViewData";
            TempData["tdMSG"] = "Passing Message through the TempData";
            return View();
        }

        public IActionResult TDDemo()
        {
            ViewBag.vbTitle = "Trying to send VB to an action.";
            ViewData["vdTitle"] = "Trying to send VD to an action.";
            TempData["tdTitle"] = "Passing msg to View via action.";
            return RedirectToAction("TDDemo_One");
        }
        public IActionResult TDDemo_One()
        {
            string vb = ViewBag.vbTitle;

            string vd = (string)ViewData["vdTitle"];
            //string vd_1 = ViewData["vdTitle"].ToString();

            string td = (string)TempData["tdTitle"];
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCDemo/Controllers/StudentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Models;
using Newtonsoft.Json;

namespace MVCDemo.Controllers
{
    public class StudentController : Controller
    {
       
        private readonly ILogger<StudentController> _logger;

        public StudentController(ILogger<StudentController> logger)
        {
            _logger = logger;
        }
        List<Student> Students = new List<Student>()
        {
            new Student(1,"Shehan", "Male", 38),
            new Student(2,"Marika", "Female", 20),
            new Student(3,"Nadeeka", "Female", 28),
            new Student(4,"Kadri", "Male", 34),
            new Student(5,"Igor", "Male", 18),
            new Student(6,"Asa", "Female", 22),
            new Student(7,"Shrddha", "Female", 20),
            new Student(8,"Mehreen", "Female", 20),
            new Student(9,"Haitham", "Male", 20)

        };
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("sList") != null)
            {
                List<Student> StudentList = JsonConvert.DeserializeObject<List<Student>>(HttpContext.Session.GetString("sList"));
                return View(StudentList);
            }
            else
            {
                return View(Students);
            }
        }

        public IActionResult StudentList()
        { 
            var studentList = Students.OrderBy(s => s.Name).ToList();
            return View(studentList);
        }

        public IActionResult Greet()
        {
            return View();
        }

        public IActionResult DisplayStudent()
        {
            return View(Students);
        }

        public IActionResult Details(int id)
        {
            var student = Students.FirstOrDefault(s=>s.SId == id);
            return View(student);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student student)
        {
            if (HttpContext.Session.GetString("sList") != null)
            {
                List<Student> StudentList = JsonConvert.DeserializeObject<List<Student>>(HttpContext.Session.GetString("sList"));

                var s = StudentList.LastOrDefault();
                student.SId = s.SId + 1;
                StudentList.Add(student);
                HttpContext.Session.SetString("sList", JsonConvert.SerializeObject(StudentList));
            }
            else
            {
                var s = Students.LastOrDefault();
                student.SId = s.SId + 1;
                Students.Add(student);
                HttpContext.Session.SetString("sList", JsonConvert.SerializeObject(Students));
            }
           
            

           
            return RedirectToAction("Index");
        }

    }
}

MVCDemo/Views/Assignment/FeverCheck.cshtml
@model MVCDemo.Models.Fever

@{
    ViewData["Title"] = "FeverCheck";
}

<h1>Free Fever Test For You</h1>
<h2>@Model.TestResult</h2>
<hr />
<div class="row"> 
    <div class="col-md-4">
        <form asp-action="FeverCheck">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BTemp" class="control-label"></label>
                <input asp-for="BTemp" class="form-control" />
                <span asp-validation-for="BTemp" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="TestResult" class="control-label"></label>
                <input asp-for="TestResult" class="form-control" />
                <span asp-validation-for="TestResult" class="text-danger"></span>
            </div> *@
            <div class="form-group top-bottom-margin">
                <input type="submit" value="Check your fever" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Assignments</a>
</div>

MVCDemo/Views/Assignment/GuessGame.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;


@model MVCDemo.Models.GuessNumber
@{
    ViewData["Title"] = "GuessGame";
}

<h1>I chose a number between 1 to 500, try to guess it!</h1>

<hr />

<h2>@Model.Msg</h2>
<div class="row">
    @{
        if(HttpContextAccessor.HttpContext.Session.GetInt32("sNumber") != null)
        {
                <div class="col-md-4">
                    <form asp-action="GuessGame">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="GuessNum" class="control-label"></label>
                            <input asp-for="GuessNum" class="form-control" />
                            <span asp-validation-for="GuessNum" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                        </div>
                    <div class="form-group top-bottom-margin">
                            <input type="submit" value="Try It" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
        }
        else
        {
            <div class="col-md-4">
              @Html.ActionLink("Re Play", "GuessGame", "Assignment", null, new { @class = "btn btn-success" })
            </div>
        }
    }
</div>

<div>
    <a asp-action="Index">Back to Assignment</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCDemo/Views/Assignment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Exercises</h1>
<div class="top-bottom-margin">
    <a class="btn btn-primary" asp-area="" asp-controller="Assignment" asp-action="FeverCheck"> EX1 - Fever Test </a>
    <a class="btn btn-warning" href="/Assignment/FeverCheck"> EX1 - Fever Test </a>

    @Html.ActionLink("EX1 - Fever Test", "FeverCheck", "Assignment", null, new { @class = "btn btn-success" })
</div>

<div class="top-bottom-margin">
    <a class="btn btn-success" asp-area="" asp-controller="Assignment" asp-action="GuessGame"> EX2 - Guess Number </a>
</div>

MVCDemo/Views/Demo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index of Demo</h1>

MVCDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    @{
        string vbMessage = ViewBag.vbMSG;

        string vdMessage = (string)ViewData["vdMSG"];
        //string vdMessage_1 = (string)ViewData["vdMSG"].ToString();

        string tdMessage = (string)TempData["tdMSG"];
    }
    <h1>ViewBag, ViewData and TempData Demo</h1>

    <h3>@ViewBag.vbMSG</h3><br />
    <h3>@ViewData["vdMSG"]</h3><br />
    <h3>@TempData["tdMSG"]</h3>
</div>

MVCDemo/Views/Home/TDDemo_One.cshtml
@{
    ViewData["Title"] = "TDDemo_One";
}

<h1>ViewBag, ViewData and TempData Demo</h1>

<h3>ViewBag: @ViewBag.vbTitle</h3>
<br />
<h3>ViewData: @ViewData["vdTitle"]</h3>
<br />
<h3>TempData: @TempData["tdTitle"]</h3>

MVCDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"> Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"> Privacy </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index"> Demo-Index </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Greet"> Greet </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index"> Assignment </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @* <h1>Greet Message: @ViewData["greet"]</h1> *@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCDemo/Views/Shared/_SpringLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCDemo.styles.css" asp-append-version="true" />
</head>
<body style="background-color:hotpink">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCDemo/Views/Shared/_StudentPartial.cshtml
@model MVCDemo.Models.Student

<div>
    <h4>@Model.Name</h4>
    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SId)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
   
</div>
@* <div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div> *@

MVCDemo/Views/Shared/_SummerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCDemo.styles.css" asp-append-version="true" />
</head>
<body style="background-color:forestgreen">
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index"> Demo-Index </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Greet"> Greet </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCDemo/Views/Student/Create.cshtml
@model MVCDemo.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="SId" class="control-label"></label>
                <input asp-for="SId" class="form-control" />
                <span asp-validation-for="SId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVCDemo/Views/Student/Details.cshtml
@model MVCDemo.Models.Student;
@{
    ViewData["Title"] = "Details";
}

@Html.Partial("_StudentPartial", Model)

MVCDemo/Views/Student/DisplayStudent.cshtml
@model IEnumerable<MVCDemo.Models.Student>
@{
    ViewData["Title"] = "DisplayStudent";
}


@foreach (var student in Model)
{
    <partial name="_StudentPartial" model="student"></partial>
    @* @await Html.PartialAsync("_StudentPartial", student) *@
    @* @Html.Partial("_StudentPartial", student) *@
    <hr/>
}

MVCDemo/Views/Student/Greet.cshtml
@{
    ViewData["Title"] = "Greet";
    Layout = "~/Views/Shared/_SummerLayout.cshtml";
}

<h1>Welcome to .Net MVC</h1>

MVCDemo/Views/Student/Index.cshtml
@model IEnumerable<MVCDemo.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new {  id=item.SId  }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MVCDemo/Views/Student/StudentList.cshtml
@model IEnumerable<MVCDemo.Models.Student>
@{
    ViewData["Title"] = "StudentList";
 }

<h1>StudentList</h1>

@{
    int i = 1;
}
 @foreach  ( var s in Model)
{
     <h3>@i) @s.SId : @s.Name</h3><br />
     i++;
} 